
export enum COLORS {
  main = "text-am-main-blue bg-am-main-blue-light border-am-main-blue",
  green = "text-am-new-green-dark bg-am-new-green-light border-am-new-green-dark",
  orange = "text-am-new-orange-dark bg-am-new-orange-light border-am-new-orange-dark",
  gray = "text-am-gray-dark bg-am-gray-light border-am-gray-dark",
  teal = "text-am-teal-dark bg-am-teal-light border-am-teal-dark",
  purple = "text-am-new-purple-dark bg-am-new-purple-light border-am-new-purple-dark",
  red = "text-am-new-red-dark bg-am-new-red-light border-am-new-red-dark",
  yellow = "text-am-new-yellow-dark bg-am-new-yellow-light border-am-new-yellow-dark",
  pink = "text-am-new-pink-dark bg-am-new-pink-light border-am-new-pink-dark",
  coral = "text-am-coral-dark bg-am-coral-light border-am-coral-dark",
  fruitA = '#8fae3f',
  fruitB = '#74452f',
  fruitC = '#8a552f',
  fruitD = '#d99a27',
  fruitE = '#6d9b43',
  fruitF = '#d66b61',
  fruitG = '#e79a23',
  fruitH = '#c68a23',
  fruitI = '#6b3b74',
  fruitJ = '#df7e24',
  fruitK = '#d8aa2b',
  fruitL = '#d96668',
  fruitM = '#f3c623',
  fruitN = '#b94b3c',
  fruitO = '#d7a52d',
}

/** Accent colors used by fruit cards and detail dialogs. */
export const FRUIT_COLORS: Readonly<Record<string, string>> = {
  'Arazá': COLORS.fruitA,
  'Borojó': COLORS.fruitB,
  Cacao: COLORS.fruitC,
  Granadilla: COLORS.fruitD,
  'Guanábana': COLORS.fruitE,
  Guayaba: COLORS.fruitF,
  Mango: COLORS.fruitG,
  'Maracuyá': COLORS.fruitH,
  Mora: COLORS.fruitI,
  Naranjilla: COLORS.fruitJ,
  Piña: COLORS.fruitK,
  Pitahaya: COLORS.fruitL,
  Taxo: COLORS.fruitM,
  'Tomate de árbol': COLORS.fruitN,
  Uvilla: COLORS.fruitO,
};
